"""initial_schema

Revision ID: 8a08a0dc6a86
Revises: 
Create Date: 2026-09-02 07:43:32.940325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a08a0dc6a86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('canonical_form', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('person_name', 'org_name', 'project_name', 'product_name', 'technical_term', 'acronym', 'custom_spelling', name='categoryenum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suppressed', 'deleted', 'needs_review', name='statusenum'), nullable=False),
    sa.Column('evidence_source', sa.Enum('explicit_input', 'manual_correction', name='evidencesourceenum'), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', name='confidenceenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('phonetic_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.Enum('explicit_input', 'manual_correction', name='triggertypeenum'), nullable=False),
    sa.Column('asr_text', sa.String(), nullable=True),
    sa.Column('corrected_text', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['vocabulary_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('variant_text', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('asr_error', 'user_provided', name='variantsourceenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['vocabulary_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary_variants')
    op.drop_table('evidence_log')
    op.drop_table('vocabulary_entries')
    op.drop_table('users')
    # ### end Alembic commands ###
